### PR TITLE
fix(app): Pass the swift userdefault storage to local kms store

### LINKED ISSUE #202: Add userdefault storage to implement LocalkmsStore interface in the swift (IOS)

### PR DESCRIPTION
**Pull request by talwinder50**
closes #202 

Signed-off-by: Talwinder kaur <talwinder.kaur@avast.com>

### CODE REVIEW

**Review by vkubiv — APPROVED** [review]

**Review by birtony — APPROVED** [review]

File: demo/app/ios/Runner/kmsStore.swift [hunk 1]
```diff
@@ -0,0 +1,40 @@
+//
+//  kmsStore.swift
+//  Runner
+//
+//  Created by Talwinder Kaur on 2023-01-26.
```
Comment (DRK3) [inline demo/app/ios/Runner/kmsStore.swift:5]: Should use Avast copyright here (like in the other files)

**Review by DRK3 — APPROVED** [review]
Looks good, but see my comment before merging

**Review by rolsonquadras — APPROVED** [review]
